name: fnx_config
description: A transformer to include build specific global configuration of your app.
version: 1.0.0
author: Tomas Zverina <tomucha@gmail.com>
homepage: https://github.com/fnx-io/fnx_config
environment:
  sdk: ">=1.8.0 <2.0.0"
dependencies:
  barback: ^0.15.2
  html5lib: ^0.12.0
  yaml: ^2.1.7
  crypto: ^0.9.1
dev_dependencies:
  browser: any
transformers:
- fnx_config

